graph LR

rsdmx --> SDMX
SDMX --> BIS
SDMX --> ECB
SDMX --> ESTAT
SDMX --> ESTAT_COMEXT
SDMX --> ESTAT_COMP
SDMX --> ESTAT_GROW
SDMX --> ESTAT_EMPL
SDMX --> IMF
SDMX --> OECD
SDMX --> UNICEF
SDMX --> UNCD2030
SDMX --> UNSD
SDMX --> ILO
SDMX --> WBG_WITS
SDMX --> World_Bank
SDMX --> PDH
SDMX --> ABS
SDMX --> NBB
SDMX --> INSEE
SDMX --> INEGI
SDMX --> ISTAT
SDMX --> NOMIS
SDMX --> LSD
SDMX --> NCSI
SDMX --> STAT_EE
SDMX --> BBK
SDMX --> KNOEMA
readsdmx --> SDMX
SDMX --> any_SDMX
rjstat --> JSON_STAT
JSON_STAT --> Norway
JSON_STAT --> ONS
JSON_STAT --> Sweden
JSON_STAT --> Denmark
JSON_STAT --> Greenland
JSON_STAT --> Finland
JSON_STAT --> CSO
JSON_STAT --> UNECE
JSON_STAT --> ESTAT
JSON_STAT --> Iceland
JSON_STAT --> Faroe_Islands
JSON_STAT --> FSO
JSON_STAT --> Croatia
JSON_STAT --> Latvia
JSON_STAT --> Armenia
JSON_STAT --> Macedonia
JSON_STAT --> Spain
JSON_STAT --> Bulgaria
JSON_STAT --> SURS
JSON_STAT --> World_Bank
JSON_STAT --> Japan
oecd --> OECD
sorvi --> Finland
eurostat --> ESTAT
restatapi --> ESTAT
restatapi --> ESTAT_COMEXT
restatapi --> ESTAT_PRODCOM
restatapi --> ESTAT_COMP
restatapi --> ESTAT_GROW
restatapi --> ESTAT_EMPL
acs --> US_Census_Bureau
inegiR --> INEGI
cbsodataR --> ODATA
ODATA --> CBS
cbsodata4 --> ODATA
censusapi --> US_Census_Bureau
nsoApi --> Multiple
CANSIM2R --> CANSIM
pxweb --> PX
PX --> Multiple
PxWebApiData --> PX
PX --> Norway
PX --> Sweden
PX --> Finland
pxR --> PX
PX --> px_format
rdbnomics --> DBnomics
readabs --> ABS
statcanR --> STATCAN_economic_data
cdlTools --> USDA_Cropscape_Data
csodata --> CSO
iriR --> IRI
czso --> CZSO
ipumsr --> IPUMS
eph --> Argentina_HHS
blsR --> BLS
danstat --> Denmark
